---
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Tests (optional)
        run: echo "No tests configured"

      - name: Build Docker Image
        run: docker build -t nodejs-app .

      - name: Save Docker Image
        run: docker save nodejs-app | gzip > nodejs-app.tar.gz

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: nodejs-app.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-image
          path: .

      - name: Extract Docker Image
        run: gunzip -c nodejs-app.tar.gz | docker load

      # - name: Deploy to S3
      #   run: |
      #     aws s3 sync public/ s3://your-s3-bucket-name --delete
